# Generated by Django 6.0.1 on 2026-01-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
                ('typowe_motywy', models.CharField(blank=True, max_length=200)),
                ('czy_fabularny', models.BooleanField(default=True)),
                ('ranking_popularnosci', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('kraj', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=70)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('miesiac_premiery', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1)),
                ('format_filmu', models.CharField(choices=[('D', 'DVD'), ('B', 'Blu-ray'), ('V', 'VOD')], default='D', max_length=1)),
                ('dostepne_kopie', models.PositiveIntegerField(default=1)),
                ('gatunek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalnia_filmow.gatunek')),
                ('rezyser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalnia_filmow.rezyser')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inna')], default=3)),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('wlasciciel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_filmow.stanowisko')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
    ]
