# Generated by Django 6.0.1 on 2026-01-28 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_filmow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['tytul'], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='gatunek',
            options={'ordering': ['nazwa'], 'verbose_name': 'Gatunek', 'verbose_name_plural': 'Gatunki'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Może przeglądać inne osoby'), ('change_osoba_owner', 'Może zmienić właściciela rekordu')], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='rezyser',
            options={'ordering': ['nazwisko', 'imie'], 'verbose_name': 'Reżyser', 'verbose_name_plural': 'Reżyserzy'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'ordering': ['nazwa'], 'verbose_name': 'Stanowisko', 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.RemoveField(
            model_name='gatunek',
            name='ranking_popularnosci',
        ),
        migrations.AddField(
            model_name='film',
            name='ranking_popularności',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ocena popularności (0–10).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='film',
            name='tytul',
            field=models.CharField(max_length=168),
        ),
        migrations.AlterField(
            model_name='rezyser',
            name='kraj',
            field=models.CharField(help_text='Kod kraju, np. PL, US, GB', max_length=2),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(condition=models.Q(('dostepne_kopie__gte', 0)), name='kopie_nieujemne'),
        ),
        migrations.AddConstraint(
            model_name='rezyser',
            constraint=models.UniqueConstraint(fields=('imie', 'nazwisko'), name='unique_rezyser_name'),
        ),
    ]
