# Generated by Django 6.0.1 on 2026-01-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_filmow', '0002_alter_film_options_alter_gatunek_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='ranking_popularności',
            new_name='Ocena',
        ),
    ]
