# Generated by Django 6.0.1 on 2026-01-29 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_filmow', '0003_rename_ranking_popularności_film_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Ocena',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ocena (0–10).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
