# Generated by Django 6.0.1 on 2026-01-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_filmow', '0004_alter_film_ocena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='Ocena',
        ),
    ]
